import numpy as np
x1 = np.array(['Python', 'PHP'])
x2 = np.array([' Java', ' C++'])
print(np.char.add(x1,x2))
print(np.char.multiply(x1,3))
print(type(x1))
print(np.char.lower(x1))
print(np.char.upper(x1))
print(np.char.swapcase(x1))
print(np.char.title(x2))
print(np.char.capitalize(x1))
print(np.char.center(x1, 10, fillchar='*'))
print(np.char.ljust(x1, 10, fillchar="-"))
print(np.char.rjust(x1, 10, fillchar="$"))
res=np.char.join(" ", x2)
print(res)
print(np.char.replace(x1, 'Python', 'Ruby'))
print(np.char.equal(x1, x2))
print(np.char.not_equal(x1, x2))
print(np.char.greater(x1, x2))
print(np.char.greater_equal(x1, x2))
print(np.char.less(x1, x2))
print(np.char.less_equal(x1, x2))
print(np.char.find(x1,'h'))
print(np.char.isdigit(x2))
print(np.char.islower(x1))
print(np.char.isupper(x2))
print(np.char.replace(x1,'P','='))
print(np.char.count(x1,'PHP'))
print(np.arange(2,11).reshape(3,3))
nulvector=np.zeros(10)
print(nulvector)
nulvector[6]=9
print(nulvector)
arr1=np.arange(12,38)
arr1[::-1]
print(arr1[::-1])
print(np.asfarray(arr1))
print(np.arange(10).reshape((2,5)))
print(np.ones((5,5)))
twodim=np.ones((5,5))
twodim[1:-1,1:-1]=0
print(twodim)
zeroborder=np.zeros((5,5))
zeroborder[1:-1,1:-1]=1
print(zeroborder)
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print(my_list)
my_tuple = ([8, 4, 6], [1, 2, 3])
print(np.asarray(my_tuple))
print(np.full((3,3),8))
print(np.empty((3,4)))
x=np.arange(5)
y=np.arange(2,6)
print(np.in1d(x,y))
x = np.array([[10, 20, 30], [20, 40, 50]])
print(x)
li=[]
for i in np.nditer(x):
    print(i)
    li.append(i)
print(list(li))
print(np.ravel(x))